params :
  epochs: 10
  batch_size: 32
  no_classes: 10
  input_shape: [28,28]
  metrics: accuracy
  optimizer: SGD
  validation_datasize: 5000
  loss_function: sparse_categorical_crossentropy

   
  
artifacts :
  artifact_dir: artifacts
  models_dir: model
  plot_dir: plot
  plot_name: visualization
  model_check_points_dir: checkpoints
  model_name: model.h5

logs:
  log_dir: logs
  general_dir: genral_logs
  tensorboard_dir: tensorboard_logs

